### test successfull calls
GET http://localhost:8000/v1/movies/1
Accept: application/json

### test calling all movies
GET http://localhost:8000/v1/movies


### test calling movies with filters
GET http://localhost:8000/v1/movies?genres=adventure


### test calling movies with partial name
GET http://localhost:8000/v1/movies?title=club

###
GET http://localhost:8000/v1/healthcheck
Accept: application/json

###
PUT localhost:8000/v1/movies/3
Accept: application/json

{"title": "Black Panther", "year": 2018, "runtime": "134 mins", "genres": ["action", "adventure", "sci-fi"]}

