GET http://localhost:8000/v1/movies/1
Accept: application/json

###
GET http://localhost:8000/v1/healthcheck
Accept: application/json

###
POST localhost:8000/v1/movies/
Accept: application/json

{"title": "Moana", "runtime": "102 mins", "genres": ["family", "adventure"]}

###
POST localhost:8000/v1/movies/
Accept: application/json

{"title": "Moana", "runtime": "102 mins", "genres": ["family", "adventure"]}


### Tests that will cause failures
### test for unknown field name
POST localhost:8000/v1/movies/
Accept: application/json

{"title": "Moana", "runtime": "102 mins", "genres": ["family", "adventure"], "stars": 4}


### test for max bytes error
POST localhost:8000/v1/movies
Accept: application/json

< ./large.json


### test for multiple JSON values
POST localhost:8000/v1/movies/
Accept: application/json

{"title": "Moana", "runtime": "102 mins", "genres": ["family", "adventure"]}{"title": "Tommyboy"}


### test for malformed JSON values
POST localhost:8000/v1/movies/
Accept: application/json

{"title": "Moana", "runtime": "102 mins", "genres": ["family", "adventure"]} :-()>


### test invalid runtime format
POST localhost:8000/v1/movies/
Accept: application/json

{"title": "Moana", "runtime": 102, "genres": ["family", "adventure"]}